apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "indexer.fullname" . }}
  labels:
    app: {{ include "indexer.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "indexer.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "indexer.name" . }}
    spec:
      containers:
        - name: indexer
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: config
              mountPath: /app/config.yaml
              subPath: config.yaml
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "indexer.fullname" . }}-config
